# Generated by Django 5.2.11 on 2026-04-21 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplierpayment'),
        ),
    ]
