# Generated by Django 5.2.11 on 2026-04-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='PaymentAllocation',
        ),
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
    ]
