# Generated by Django 5.2.11 on 2026-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_supplierpayment_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('CASH', 'Cash'), ('BANK', 'Bank'), ('CREDIT', 'Credit'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='active', max_length=20),
        ),
    ]
