# Generated by Django 5.2.11 on 2026-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bankaccount_banktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('gst', models.CharField(blank=True, max_length=50)),
                ('financial_year_from', models.DateField()),
                ('financial_year_to', models.DateField()),
            ],
        ),
    ]
