# Generated by Django 5.2.11 on 2026-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_address_company_country_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit', 'Credit')], default='cash', max_length=10),
        ),
    ]
