# Generated by Django 5.2.11 on 2026-05-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
