# Generated by Django 5.2.11 on 2026-05-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bill_payment_mode_alter_bill_status'),
        ('purchases', '0006_alter_supplierpayment_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bill'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
    ]
